# Generated by Django 5.0.6 on 2024-07-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('CategoryName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CategoryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductId', models.IntegerField()),
                ('ProductPrice', models.IntegerField()),
                ('ProductDate', models.DateField()),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
